# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='url',
            new_name='box',
        ),
    ]
