# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160621_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
