# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160621_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='user',
        ),
        migrations.RemoveField(
            model_name='command',
            name='shell',
        ),
        migrations.AddField(
            model_name='box',
            name='shell',
            field=models.CharField(choices=[('ZS', 'ZSH'), ('BS', 'BASH')], default=None, max_length=2),
        ),
    ]
