# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160621_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='shell',
            field=models.CharField(blank=True, choices=[('ZS', 'ZSH'), ('BS', 'BASH')], default=None, max_length=2, null=True),
        ),
    ]
