# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160621_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
